from __future__ import annotations

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, ORJSONResponse

from .analyzer import analyze_video
from .config import get_settings
from .model_loader import ModelUnavailable, VJEPAModelAdapter
from .schemas import AnalysisResult, HealthResponse
from .storage import Storage
from .video_io import VideoReadError

import subprocess

settings = get_settings()
storage = Storage(settings.data_dir)
model = VJEPAModelAdapter(settings, autoload=settings.load_model_on_startup)

app = FastAPI(
    title="V-JEPA Video Risk Lens API",
    version="0.1.0",
    default_response_class=ORJSONResponse,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/api/health", response_model=HealthResponse)
def health() -> HealthResponse:
    return HealthResponse(
        ok=True,
        model_backend=model.backend,
        model_loaded=model.loaded,
        device=str(model.device),
        model_dir=settings.model_dir,
        allow_demo_fallback=settings.allow_demo_fallback,
        errors=model.errors,
        discovered_model_files=model.refresh_discovery(),
        load_attempted=model.load_attempted,
    )


def _is_video_upload(upload: UploadFile) -> bool:
    if (upload.content_type or "").startswith("video/"):
        return True
    name = (upload.filename or "").lower()
    return name.endswith((".mp4", ".mov", ".m4v", ".avi", ".webm", ".mkv"))


@app.post("/api/preview")
async def preview(video: UploadFile = File(...)) -> FileResponse:
    """Return a browser-compatible MP4 preview.

    Some demo videos generated by OpenCV use mp4v or other codecs that the
    browser <video> element may not decode even though OpenCV/FastAPI can read
    them. This endpoint transcodes the uploaded file to H.264/yuv420p MP4 using
    ffmpeg so the frontend preview is reliable.
    """
    if not _is_video_upload(video):
        raise HTTPException(status_code=400, detail="Upload a video file: mp4, mov, webm, avi, or mkv.")

    preview_id, input_path = await storage.save_upload(video)
    preview_dir = storage.root / "previews"
    preview_dir.mkdir(parents=True, exist_ok=True)
    output_path = preview_dir / f"{preview_id}_preview.mp4"

    cmd = [
        "ffmpeg",
        "-y",
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        str(input_path),
        "-vf",
        "scale='min(1280,iw)':-2",
        "-an",
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-crf",
        "23",
        "-pix_fmt",
        "yuv420p",
        "-movflags",
        "+faststart",
        str(output_path),
    ]

    try:
        completed = subprocess.run(cmd, check=False, capture_output=True, text=True, timeout=120)
    except subprocess.TimeoutExpired as exc:
        raise HTTPException(status_code=504, detail="Preview conversion timed out.") from exc

    if completed.returncode != 0 or not output_path.exists() or output_path.stat().st_size == 0:
        detail = completed.stderr.strip() or "ffmpeg failed to create a preview."
        raise HTTPException(status_code=500, detail=f"Preview conversion failed: {detail}")

    return FileResponse(
        path=output_path,
        media_type="video/mp4",
        filename=f"{preview_id}_preview.mp4",
        headers={"Cache-Control": "no-store"},
    )


@app.post("/api/analyze", response_model=AnalysisResult)
async def analyze(
    video: UploadFile = File(...),
    demo_mode: bool = Form(False),
    domain_mode: str = Form("auto"),
) -> AnalysisResult:
    if not _is_video_upload(video):
        raise HTTPException(status_code=400, detail="Upload a video file: mp4, mov, webm, avi, or mkv.")
    analysis_id, path = await storage.save_upload(video)
    try:
        # Load lazily so /api/health never turns into a Vite proxy 502 while
        # torch.hub builds the architecture or reads a checkpoint.
        if not model.loaded and not (demo_mode and settings.allow_demo_fallback):
            model.ensure_loaded()
        result = analyze_video(
            path=path,
            original_filename=video.filename or path.name,
            analysis_id=analysis_id,
            settings=settings,
            model=model,
            demo_mode=demo_mode,
            domain_mode=domain_mode,
        )
    except ModelUnavailable as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except VideoReadError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=500, detail=f"Analysis failed: {type(exc).__name__}: {exc}") from exc
    storage.save_result(analysis_id, result.model_dump())
    return result
